fiterlatam/web-app

config/start.sh
=> Correct carriage return

src/app/app.module.ts, src/app/clientsallies/clientsallies-routing.module.ts, src/app/clientsallies/clientsallies.component.html, src/app/clientsallies/clientsallies.component.ts, src/app/clientsallies/clientsallies.module.ts, src/app/clientsallies/clientsallies.service.ts, src/app/clientsallies/create-clientally/create-clientally.component.html, src/app/clientsallies/create-clientally/create-clientally.component.spec.ts, src/app/clientsallies/create-clientally/create-clientally.component.ts, src/app/clientsallies/edit-clientally/edit-clientally.component.html, src/app/clientsallies/edit-clientally/edit-clientally.component.spec.ts, src/app/clientsallies/edit-clientally/edit-clientally.component.ts, src/app/core/shell/toolbar/toolbar.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
feature/SU-47 - Campos creación Aliados
=> feature/SU-47 - Campos creación Aliados

.gitignore, src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.html, src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.ts, src/app/clients/client-stepper/client-general-step/client-general-step.component.ts, src/app/clients/clients-view/clients-view.component.html, src/app/clients/create-client/create-client.component.html, src/app/core/core.module.ts, src/app/core/shell/breadcrumb/breadcrumb.component.html, src/app/pipes/date-format.pipe.spec.ts, src/app/pipes/datetime-format.pipe.spec.ts, src/app/pipes/format-display-name.pipe.spec.ts, src/app/pipes/format-display-name.pipe.ts, src/app/pipes/pipes.module.ts, src/app/shared/form-dialog/form-dialog.component.html, src/app/shared/form-dialog/formfield/formfield.component.html, src/app/shared/form-dialog/formfield/formfield.component.ts, src/app/shared/form-dialog/formfield/model/formfield-base.ts, src/app/shared/tabs/entity-datatable-tab/datatable-multi-row/datatable-multi-row.component.html, src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.html, src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json, src/environments/environment.ts
Feature/SU-48: Campos creación clientes (empresas)
Jira Task: https://fiterio.atlassian.net/browse/SU-48
=> Feature/SU-48: Campos creación clientes (empresas)

src/app/core/utils/datatables.ts, src/app/pipes/format-display-name.pipe.ts
Feature/SU-48: Entity client data-table update
=> Feature/SU-48: Entity client data-table update

src/app/app.module.ts, src/app/clientsallies/clientsallies-routing.module.ts, src/app/clientsallies/clientsallies.component.html, src/app/clientsallies/edit-clientally/edit-clientally.component.html, src/app/clientsallies/edit-clientally/edit-clientally.component.ts, src/app/clientsalliespointofsales/clientallypointofsales-routing.module.ts, src/app/clientsalliespointofsales/clientallypointofsales.component.html, src/app/clientsalliespointofsales/clientallypointofsales.component.ts, src/app/clientsalliespointofsales/clientallypointofsales.module.ts, src/app/clientsalliespointofsales/clientallypointofsales.service.ts, src/app/clientsalliespointofsales/create-clientallypointofsales/create-clientallypointofsales.component.html, src/app/clientsalliespointofsales/create-clientallypointofsales/create-clientallypointofsales.component.spec.ts, src/app/clientsalliespointofsales/create-clientallypointofsales/create-clientallypointofsales.component.ts, src/app/clientsalliespointofsales/edit-clientallypointofsales/edit-clientallypointofsales.component.html, src/app/clientsalliespointofsales/edit-clientallypointofsales/edit-clientallypointofsales.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
feature/SU-49 - Campos creación Puntos de venta
=> feature/SU-49 - Campos creación Puntos de venta

src/app/clientsallies/clientsallies-routing.module.ts, src/app/clientsallies/create-clientally/create-clientally.component.html, src/app/clientsallies/create-clientally/create-clientally.component.ts, src/app/clientsallies/edit-clientally/edit-clientally.component.html, src/app/clientsallies/edit-clientally/edit-clientally.component.ts, src/app/clientsalliespointofsales/clientallypointofsales-routing.module.ts
feature/SU-47-02 - New validation on CupoMaxSell
=> feature/SU-47-02 - New validation on CupoMaxSell

src/app/clients/client-stepper/client-general-step/client-general-step.component.html, src/app/clients/client-stepper/client-general-step/client-general-step.component.ts, src/app/clients/edit-client/edit-client.component.html
Feature/SU-48: Make constitution optional
=> Feature/SU-48: Make constittution optional

src/app/clientsallies/clientsallies-routing.module.ts, src/app/clientsallies/clientsallies.component.html, src/app/clientsallies/clientsallies.module.ts, src/app/clientsalliespointofsales/clientallypointofsales.component.html, src/app/organization/bulk-import/bulk-import.component.html, src/app/organization/bulk-import/view-bulk-import/bulk-imports.ts, src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
feature/SU-12-13 - Comercios aliados: Registro de empresa matriz + Puntos de Ventas
=> feature/SU-12-13 - Comercios aliados: Registro de empresa matriz + Puntos de Ventas

src/app/loans/loan-assignor-selector/loan-assignor-selector.component.html, src/app/loans/loan-assignor-selector/loan-assignor-selector.component.spec.ts, src/app/loans/loan-assignor-selector/loan-assignor-selector.component.ts, src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html, src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts, src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html, src/app/loans/loans-view/general-tab/general-tab.component.html, src/app/loans/loans-view/general-tab/general-tab.component.ts, src/app/loans/loans.module.ts, src/app/products/loan-products/loan-product-stepper/loan-product-accounting-step/loan-product-accounting-step.component.ts, src/app/shared/models/general.model.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-209
=> Feature/SU-209: Asociación de Cedente (Empresas) a préstamos

src/app/products/products.component.html
Implemented Spanish translation in the Products view. 
SU-208
=> SU-208 - Agregar traducciones faltantes para español

src/app/reports/run-report/table-and-sms/table-and-sms.component.html, src/app/reports/run-report/table-and-sms/table-and-sms.component.scss
Jira Task: https://fiterio.atlassian.net/browse/SU-129
=> Bug/SU-129: Reporte de tabla de auditoria: Roles & Usuarios.

src/app/users/deactivate-user-dialog/deactivate-user-dialog.component.html, src/app/users/view-user/view-user.component.ts
Jira Task: https://fiterio.atlassian.net/browse/SU-10
=> Bug/SU-10: Usuarios: inactivación (temporal/definitiva)

src/app/clientsallies/clientsallies.component.html
feature/SU-15 - Comercios aliados: Registro de empresa matriz
=> feature/SU-15 - Comercios aliados: Registro de empresa matriz

src/app/clients/client-stepper/client-general-step/client-general-step.component.html, src/app/clients/client-stepper/client-general-step/client-general-step.component.ts, src/app/clients/edit-client/edit-client.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-214
=> Enhancements/SU-214: orrecciones - Sprint 3

Jenkinsfile, config/start.sh, scripts/generate-playbook.sh
=> Merge SU+ QA branch

src/app/shared/data-selector/data-selector.component.ts
Jira Task: https://fiterio.atlassian.net/browse/SU-213
=> Enhancements/SU-213: Mejoras / Improvements - Sprint 3

src/app/pipes/yesno.pipe.ts, src/app/products/charges/charges.component.html, src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/edit-charge/edit-charge.component.html, src/app/products/charges/view-charge/view-charge.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-67
=> Fearture/SU-67: Seguros obligatorios - parametrización y cálculo

src/app/clientsallies/create-clientally/create-clientally.component.html, src/app/clientsallies/create-clientally/create-clientally.component.ts, src/app/clientsallies/edit-clientally/edit-clientally.component.html, src/app/clientsallies/edit-clientally/edit-clientally.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
fix/SU-215 - pre validation fixes
=> fix/SU-215 - pre validation fixes

src/app/clients/clients-view/clients-view.component.html, src/app/clients/clients-view/clients-view.component.ts, src/app/clients/clients.component.html, src/app/clients/clients.component.ts
=> SU-26 : Cliente: Estado CANCELADO

src/app/clients/clients-view/client-actions/block-client/block-client.component.html, src/app/clients/clients-view/client-actions/block-client/block-client.component.scss, src/app/clients/clients-view/client-actions/block-client/block-client.component.spec.ts, src/app/clients/clients-view/client-actions/block-client/block-client.component.ts, src/app/clients/clients-view/client-actions/client-actions.component.html, src/app/clients/clients-view/client-actions/client-actions.component.ts, src/app/clients/clients-view/client-actions/undo-block-client/undo-block-client.component.html, src/app/clients/clients-view/client-actions/undo-block-client/undo-block-client.component.scss, src/app/clients/clients-view/client-actions/undo-block-client/undo-block-client.component.spec.ts, src/app/clients/clients-view/client-actions/undo-block-client/undo-block-client.component.ts, src/app/clients/clients-view/clients-view.component.html, src/app/clients/clients-view/clients-view.component.ts, src/app/clients/clients.module.ts, src/app/clients/common-resolvers/client-actions.resolver.ts, src/app/clientsallies/create-clientally/create-clientally.component.ts, src/app/clientsallies/edit-clientally/edit-clientally.component.ts, src/app/pipes/status-lookup.pipe.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-28
=> Feature/SU-28: Cliente: Bloqueo por FALLECIMIENTO (m)

src/app/system/manage-blocking-reasons/create-manage-blocking-reasons/create-manage-blocking-reasons.component.html, src/app/system/manage-blocking-reasons/create-manage-blocking-reasons/create-manage-blocking-reasons.component.ts, src/app/system/manage-blocking-reasons/create-manage-blocking-reasons/manage-blocking-reasons-template.resolver.ts, src/app/system/manage-blocking-reasons/manage-blocking-reasons.component.html, src/app/system/manage-blocking-reasons/manage-blocking-reasons.component.ts, src/app/system/manage-blocking-reasons/view-manage-blocking-reasons/view-manage-blocking-reasons.component.html, src/app/system/system.service.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> Make name of Reason

src/app/clients/client-blocking-reason-dialog/client-blocking-reason-dialog.component.html, src/app/clients/client-blocking-reason-dialog/client-blocking-reason-dialog.component.spec.ts, src/app/clients/client-blocking-reason-dialog/client-blocking-reason-dialog.component.ts, src/app/clients/clients.component.html, src/app/clients/clients.component.ts, src/app/clients/clients.module.ts, src/app/clients/clients.service.ts
=> SU-43 : Cliente: Estado BLOQUEADO

src/app/products/maximum-credit-rate/edit-maximum-credit-rate/edit-maximum-credit-rate.component.html, src/app/products/maximum-credit-rate/edit-maximum-credit-rate/edit-maximum-credit-rate.component.scss, src/app/products/maximum-credit-rate/edit-maximum-credit-rate/edit-maximum-credit-rate.component.ts, src/app/products/maximum-credit-rate/view-maximum-credit-rate.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> Bug/SU-152: Actualizar motivo de bloqueo

src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts, src/app/products/loan-products/models/loan-product.model.ts
=> SU-53 : Frecuencia de pago Su+ pay - Días no hábiles

src/app/clients/clients-view/client-actions/block-client/block-client.component.html, src/app/clients/clients-view/client-actions/block-client/block-client.component.ts, src/app/clients/clients-view/client-actions/undo-block-client/undo-block-client.component.html, src/app/clients/clients-view/client-actions/undo-block-client/undo-block-client.component.ts, src/app/clients/clients-view/clients-view.component.html, src/app/clients/clients.service.ts, src/app/clients/common-resolvers/client-actions.resolver.ts, src/app/system/manage-blocking-reasons/block-by-control-lists/block-by-control-lists.component.ts, src/app/system/manage-blocking-reasons/manage-blocking-reasons.component.html, src/app/system/manage-blocking-reasons/manage-blocking-reasons.component.ts, src/app/system/manage-blocking-reasons/view-manage-blocking-reasons/view-manage-blocking-reasons.component.ts, src/app/system/system-routing.module.ts, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-223
=> Bugs/SU-223: Sprint 6 - Fixes

src/app/products/maximum-credit-rate/edit-maximum-credit-rate/edit-maximum-credit-rate.component.html, src/app/products/maximum-credit-rate/edit-maximum-credit-rate/edit-maximum-credit-rate.component.ts, src/app/products/maximum-credit-rate/view-maximum-credit-rate.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-21
=> Feature/SU-21: Control tasas de interés corriente y de interés de mora

src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-35 Correct product display

src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
=> SU-37 Add amount for arrears consideration

src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html, src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-57 : Sistema de amortización (su+ factoring)

src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-38 Add payment type

src/app/clients/clients-view/general-tab/general-tab.component.html, src/app/clients/clients-view/general-tab/general-tab.component.ts, src/app/loans/loans-view/loans-view.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-41 Add cancelled status

src/app/clients/clients-view/clients-view.component.html, src/app/clients/clients-view/clients-view.component.ts, src/app/clients/clients-view/general-tab/general-tab.component.html, src/app/clients/clients-view/general-tab/general-tab.component.ts
=> SU-222 : Detalles del cliente y crédito / Client and Credit Details

src/app/clients/clients-view/clients-view.component.ts, src/app/clients/clients.service.ts, src/app/system/manage-blocking-reasons/manage-blocking-reasons.component.html, src/app/system/manage-blocking-reasons/unblock-clients/unblock-clients.component.html, src/app/system/manage-blocking-reasons/unblock-clients/unblock-clients.component.spec.ts, src/app/system/manage-blocking-reasons/unblock-clients/unblock-clients.component.ts, src/app/system/system-routing.module.ts, src/app/system/system.module.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-224 : Massive unblock

src/app/clients/clients-view/general-tab/general-tab.component.html, src/app/clients/clients-view/general-tab/general-tab.component.ts, src/app/loans/common-resolvers/loan-action-button.resolver.ts, src/app/loans/loans-view/loan-account-actions/block-loan/block-loan.component.html, src/app/loans/loans-view/loan-account-actions/block-loan/block-loan.component.scss, src/app/loans/loans-view/loan-account-actions/block-loan/block-loan.component.spec.ts, src/app/loans/loans-view/loan-account-actions/block-loan/block-loan.component.ts, src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html, src/app/loans/loans.module.ts, src/app/loans/loans.service.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-42 Add loan blocking

src/app/system/codes/view-code/view-code.component.html, src/app/system/codes/view-code/view-code.component.ts
=> SU-227 : Code Values

src/app/clientsallies/create-clientally/create-clientally.component.html, src/app/clientsallies/create-clientally/create-clientally.component.ts, src/app/clientsallies/edit-clientally/edit-clientally.component.html, src/app/clientsallies/edit-clientally/edit-clientally.component.ts
=> SU-233 Allow 0 for ally settled commission

src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/create-loan-product/create-loan-product.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.ts, src/app/products/loan-products/models/loan-product.model.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-51
=> Feature/SU-51: Creación cupo para avances | Creation of quota for advances

src/app/loans/models/loan-account.model.ts, src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/create-loan-product/create-loan-product.component.ts, src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.ts, src/app/products/products.service.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
feature/SU-55 - Transacciones habilitadas
=> feature/SU-55 - Transacciones habilitadas

src/app/clients/client-stepper/client-general-step/client-general-step.component.html, src/app/clients/client-stepper/client-general-step/client-general-step.component.ts, src/app/clients/clients-view/general-tab/general-tab.component.html, src/app/clients/clients-view/general-tab/general-tab.component.ts, src/app/clients/edit-client/edit-client.component.html, src/app/clients/edit-client/edit-client.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-78
=> Feature/SU-78: Liberación de Cupo | Quota Release

src/app/clients/client-stepper/client-general-step/client-general-step.component.html, src/app/clients/client-stepper/client-general-step/client-general-step.component.ts, src/app/clients/edit-client/edit-client.component.html, src/app/clients/edit-client/edit-client.component.ts
=> SU-234 : Client - Create and Edit

src/app/system/manage-blocking-reasons/unblock-clients/unblock-clients.component.html, src/app/system/manage-blocking-reasons/unblock-clients/unblock-clients.component.ts, src/assets/translations/es-MX.json
=> SU-241 : DEMO 8 - Block Findings

src/app/products/maximum-credit-rate/edit-maximum-credit-rate/edit-maximum-credit-rate.component.html, src/app/products/maximum-credit-rate/edit-maximum-credit-rate/edit-maximum-credit-rate.component.ts, src/app/products/maximum-credit-rate/view-maximum-credit-rate.component.html
Jira Task: https://fiterio.atlassian.net/browse/SU-230
=> Enhancements/SU-48: Refactorizar pantalla de Tasa Legal Máxima | Refactor Maximum Legal Rate screen

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-238
=> Feature/SU-238: Recalculation of payment plan due to change in maximum usury rate

src/app/app.module.ts, src/app/system/manage-channels/channel-routing.module.ts, src/app/system/manage-channels/channel.component.html, src/app/system/manage-channels/channel.component.ts, src/app/system/manage-channels/channel.module.ts, src/app/system/manage-channels/channel.service.ts, src/app/system/manage-channels/create-channel/create-channel.component.html, src/app/system/manage-channels/create-channel/create-channel.component.ts, src/app/system/manage-channels/edit-channel/edit-channel.component.html, src/app/system/manage-channels/edit-channel/edit-channel.component.ts, src/app/system/manage-channels/manage-subchannels/create-subchannel/create-subchannel.component.html, src/app/system/manage-channels/manage-subchannels/create-subchannel/create-subchannel.component.ts, src/app/system/manage-channels/manage-subchannels/edit-subchannel/edit-subchannel.component.html, src/app/system/manage-channels/manage-subchannels/edit-subchannel/edit-subchannel.component.ts, src/app/system/manage-channels/manage-subchannels/subchannel-routing.module.ts, src/app/system/manage-channels/manage-subchannels/subchannel.component.html, src/app/system/manage-channels/manage-subchannels/subchannel.component.ts, src/app/system/manage-channels/manage-subchannels/subchannel.module.ts, src/app/system/manage-channels/manage-subchannels/subchannel.service.ts, src/app/system/system.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
feature/SU-54 - Canales y comercios de compra/avances autorizados
=> feature/SU-54 - Canales y comercios de compra/avances autorizados

src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html, src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts, src/app/loans/loans-view/account-details/account-details.component.html, src/app/loans/loans-view/account-details/account-details.component.ts, src/app/loans/loans-view/loans-view.component.ts, src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-terms-step/loan-product-terms-step.component.ts, src/app/products/loan-products/models/loan-product.model.ts, src/app/shared/models/general.model.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Tasks:
https://fiterio.atlassian.net/browse/SU-235
https://fiterio.atlassian.net/browse/SU-231
=> Feature/SU-235-231: Ajuste en Gestión de Productos | Adjustment in Product Management

src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.ts, src/app/products/charges/view-charge/view-charge.component.html, src/app/products/products-routing.module.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-246
=> Bugs/SU-246: Charges - Comma and Dot decimals

src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/customcharges/customchargetypemap.component.ts, src/assets/translations/es-MX.json
fix/SU-236 - Creacion de cargo - Otro cargo - missing item 2
=> fix/SU-236 - Creacion de cargo - Otro cargo - missing item 2

package-lock.json, package.json, src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.ts, src/app/system/manage-channels/channel-routing.module.ts, src/app/system/manage-channels/channel.component.html, src/app/system/manage-channels/channel.component.ts, src/app/system/manage-channels/channel.service.ts, src/app/system/manage-channels/create-channel/create-channel.component.html, src/app/system/manage-channels/create-channel/create-channel.component.ts, src/app/system/manage-channels/create-channel/create-channel.resolver.ts, src/app/system/manage-channels/edit-channel/edit-channel.component.html, src/app/system/manage-channels/edit-channel/edit-channel.component.ts, src/app/system/system-routing.module.ts, src/app/system/system.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-247
=> Feature/SU-247: Canales Compra/Avance- Channel BUY/Advance (Continue SU-54)

src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts, src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html, src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts, src/app/loans/loans-view/loan-account-actions/disburse/disburse.component.ts, src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.html, src/app/products/charges/edit-charge/edit-charge.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-237
=> Bugs/SU-237: Buy validation - Maximum Rate

src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.html, src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.ts, src/app/clientsallies/clientsallies.component.html, src/app/clientsallies/clientsallies.component.ts, src/app/clientsalliespointofsales/clientallypointofsales-routing.module.ts, src/app/clientsalliespointofsales/clientallypointofsales.component.html, src/app/clientsalliespointofsales/clientallypointofsales.component.ts, src/app/clientsalliespointofsales/clientallypointofsales.service.ts, src/app/clientsalliespointofsales/create-clientallypointofsales/create-clientallypointofsales.component.html, src/app/clientsalliespointofsales/create-clientallypointofsales/create-clientallypointofsales.component.ts, src/app/core/utils/datatables.ts, src/app/products/customcharges/customchargetypemap.component.ts, src/app/shared/data-selector/data-selector.component.html, src/app/shared/form-dialog/form-group.service.ts, src/app/shared/form-dialog/formfield/formfield.component.html, src/app/shared/form-dialog/formfield/formfield.component.ts, src/app/shared/form-dialog/formfield/model/formfield-base.ts, src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.ts, src/app/system/manage-channels/manage-subchannels/subchannel.component.html, src/app/system/manage-channels/manage-subchannels/subchannel.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-220
=> Bugs/SU-220: Agregar máscara en dataTables | Add mask on dataTables

src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.html, src/app/products/charges/edit-charge/edit-charge.component.ts, src/app/products/interest-rates/create-interest-rate/create-interest-rate.component.html, src/app/products/interest-rates/create-interest-rate/create-interest-rate.component.ts, src/app/products/interest-rates/edit-interest-rate/edit-interest-rate.component.html, src/app/products/interest-rates/edit-interest-rate/edit-interest-rate.component.ts, src/app/products/interest-rates/interest-rate-history/interest-rate-history.component.html, src/app/products/interest-rates/interest-rate-history/interest-rate-history.component.ts, src/app/products/interest-rates/interest-rate-template.resolver.ts, src/app/products/interest-rates/interest-rates.component.html, src/app/products/interest-rates/interest-rates.component.ts, src/app/products/interest-rates/view-interest-rate/view-interest-rate.component.html, src/app/products/products.service.ts, src/app/shared/form-dialog/formfield/formfield.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Bugs/SU-247-246: Bug fixes for SU-247 & 246
=> Bugs/SU-247-246: Bug fixes for SU-247 & 246

src/app/clientsalliespointofsales/create-clientallypointofsales/create-clientallypointofsales.component.html, src/app/clientsalliespointofsales/create-clientallypointofsales/create-clientallypointofsales.component.ts, src/app/clientsalliespointofsales/edit-clientallypointofsales/edit-clientallypointofsales.component.html, src/app/clientsalliespointofsales/edit-clientallypointofsales/edit-clientallypointofsales.component.ts
=> [SU-251] increase Points of Sales Field length to maximum of 6

src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.html, src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts, src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.html, src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.ts, src/app/products/loan-products/create-loan-product/create-loan-product.component.ts, src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts, src/app/web-app.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-100
Use channelName instead of channelHash
=> Feature/SU-100: Canales de recaudo - Parametrización a nivel prod

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-99 : Canales de recaudo - Habilitación

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira task: https://fiterio.atlassian.net/browse/SU-102
=> Feature/SU-102: Canal tiendas físicas de comercios aliados

src/app/loans/loans-routing.module.ts, src/app/loans/loans-view/transactions/undo-transactions/undo-transactions.component.html, src/app/loans/loans-view/transactions/undo-transactions/undo-transactions.component.spec.ts, src/app/loans/loans-view/transactions/undo-transactions/undo-transactions.component.ts, src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html, src/app/loans/loans.module.ts
=> SU-114 : Anulación y reverso de pagos

src/app/clientsallies/clientsallies.service.ts, src/app/clientsallies/create-clientally/create-clientally.component.html, src/app/clientsallies/create-clientally/create-clientally.component.ts, src/app/clientsallies/edit-clientally/edit-clientally.component.html, src/app/clientsallies/edit-clientally/edit-clientally.component.ts
=> SU-262 : Change VARCHAR Length-Allies

src/assets/translations/es-MX.json
=> [SU-242] change spanish meaning of original schedule

src/assets/translations/es-MX.json
=> SU-261 : Translations

src/app/pipes/format-number.pipe.ts, src/app/products/interest-rates/create-interest-rate/create-interest-rate.component.html, src/app/products/interest-rates/create-interest-rate/create-interest-rate.component.ts, src/app/products/interest-rates/edit-interest-rate/edit-interest-rate.component.html, src/app/products/interest-rates/edit-interest-rate/edit-interest-rate.component.ts, src/environments/environment.ts
=> [SU-260] Admin - Products - Interest Rate Management - ZERO % Allow

src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.html, src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.ts
=> [SU-242]  ensured formatting of amount values for original calendar

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-238
=> Feature/SU-238: Recalculation of payment plan due to change in maximum usury rate. (FromPreviuos Sprint

src/app/clients/clients.component.html, src/app/clients/clients.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> [SU-269]  Client screen - Pantalla de Cliente

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> Bugs/SU-238: Remove Interestes Job and Refactor

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-245 add translations

src/app/loans/loans-view/account-details/account-details.component.html
=> [SU-248]  Client screen - Pantalla de Cliente

src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.html, src/app/products/charges/edit-charge/edit-charge.component.ts, src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.html, src/assets/translations/es-MX.json
=> [SU-160] Seguros obligatorios: parametrización

src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.html, src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts, src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.html, src/app/loans/loans-view/transactions/edit-transaction/edit-transaction.component.ts, src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html, src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira task: https://fiterio.atlassian.net/browse/SU-103
=> Feature/SU-103: Consignaciones bancarias | Bank deposits

src/app/loans/loans-view/loan-account-actions/make-repayment/make-repayment.component.ts, src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.html, src/app/loans/loans-view/loan-account-actions/prepay-loan/prepay-loan.component.ts
=> SU-272 : Compra y Recaudo / Buy & Pay - add prepay loan

src/app/products/customcharges/create-charge-map/create-charge-map.component.html, src/app/products/customcharges/create-charge-map/create-charge-map.component.scss, src/app/products/customcharges/create-charge-map/create-charge-map.component.spec.ts, src/app/products/customcharges/create-charge-map/create-charge-map.component.ts, src/app/products/customcharges/create-charge-map/custom-charges.resolver.ts, src/app/products/customcharges/customchargetypemap-routing.module.ts, src/app/products/customcharges/customchargetypemap.component.html, src/app/products/customcharges/customchargetypemap.component.ts, src/app/products/customcharges/customchargetypemap.module.ts, src/app/products/customcharges/customchargetypemap.service.ts, src/app/products/customcharges/delete-customchargetypemap-dialog/delete-customchargetypemap-dialog.component.ts, src/app/products/customcharges/edit-charge-map/custom-charges.resolver.ts, src/app/products/customcharges/edit-charge-map/edit-charge-map.component.html, src/app/products/customcharges/edit-charge-map/edit-charge-map.component.scss, src/app/products/customcharges/edit-charge-map/edit-charge-map.component.spec.ts, src/app/products/customcharges/edit-charge-map/edit-charge-map.component.ts, src/app/products/customcharges/view-charge-map/view-charge-map.component.html, src/app/products/customcharges/view-charge-map/view-charge-map.component.scss, src/app/products/customcharges/view-charge-map/view-charge-map.component.spec.ts, src/app/products/customcharges/view-charge-map/view-charge-map.component.ts, src/app/products/customcharges/view-charge-map/view-charge-map.resolver.ts, src/app/products/interest-rates/interest-rates.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira Task: https://fiterio.atlassian.net/browse/SU-267
=> Feature/SU-267: Mapeo de Cargos Personalizados

src/app/clients/clients.component.html, src/app/clients/clients.component.ts
=> SU-280 : Clientes / Client Screen

src/assets/translations/es-MX.json
=> [SU-287] Editing Charges - Amount field

src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.html, src/app/products/charges/edit-charge/edit-charge.component.ts
=> SU-278 : Cargos --> Seguro Voluntario / Charges --> Voluntary ensurance

src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.ts
=> Feature/SU-278 - Add IVA Config

src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-278 : Cargos --> Seguro Voluntario / Charges --> Voluntary ensuran - Add Transaltion and Round

src/app/products/maximum-credit-rate/edit-maximum-credit-rate/edit-maximum-credit-rate.component.ts
Jira task: https://fiterio.atlassian.net/browse/SU-259
=> Feature/SU-259: Maxima legal Job

src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.ts
=> [SU-287] allow edit of amount using . for es locale

src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/advance-payment-allocation-tab/advance-payment-allocation-tab.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-payment-strategy-step/payment-allocation-model.ts, src/app/products/loan-products/view-loan-product/shared/view-advance-paymeny-allocation/view-advance-paymeny-allocation.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-106 translations added for allocation types

src/app/loans/common-resolvers/loan-action-button.resolver.ts, src/app/loans/loans-view/loan-account-actions/loan-reschedule/loan-reschedule.component.html, src/app/loans/loans-view/loan-account-actions/loan-reschedule/loan-reschedule.component.ts, src/app/loans/loans.module.ts, src/app/loans/loans.service.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira task: https://fiterio.atlassian.net/browse/SU-133
=> Feature/SU-133: Rediferidos: pago alternativo

src/app/loans/loans-view/loans-view.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira task: https://fiterio.atlassian.net/browse/SU-135
=> Feature/SU-135: Rediferidos: parametrización número rediferidos

src/app/loans/loans-view/loans-view.component.html, src/app/loans/loans-view/loans-view.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> [SU-138] Reestructuraciones: identificación reestructurado

src/app/products/insurance-incident/edit-insurance-incident/edit-insurance-incident.component.ts
=> [SU-276] Gestión de novedades de seguros

src/assets/translations/es-MX.json
=> [SU-315] (demo 14 & 15) - Translation / Juicio Hipotecario

src/app/clients/clients-view/clients-view.component.html
=> SU-310: Reestructura - Permitir en Bloqueo

src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
=> SU-313 - Reestructura - Amount on top-up

src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.ts
=> fixed voluntary charge amount calculation validation issue for spanish

src/app/products/insurance-incident/create-insurance-incident/create-insurance-incident.component.html, src/app/products/insurance-incident/create-insurance-incident/create-insurance-incident.component.ts, src/app/products/insurance-incident/edit-insurance-incident/edit-insurance-incident.component.html, src/app/products/insurance-incident/edit-insurance-incident/edit-insurance-incident.component.ts, src/app/products/insurance-incident/insruance-incident-template.resolver.spec.ts, src/app/products/insurance-incident/insurance-incident-list/insurance-incident-list.component.html, src/app/products/insurance-incident/insurance-incident-list/insurance-incident-list.component.ts, src/app/products/insurance-incident/insurance-incident-template.resolver.ts, src/app/products/insurance-incident/insurance-incident.service.ts, src/app/products/insurance-incident/view-insurance-incident/view-insurance-incident.component.html, src/app/products/products-routing.module.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-173 initial commit to add incident type

src/app/reports/reports.module.ts, src/app/reports/run-report/run-report.component.scss, src/app/reports/run-report/table-and-sms/table-and-sms.component.html, src/app/reports/run-report/table-and-sms/table-and-sms.component.ts
Jira tasks: https://fiterio.atlassian.net/browse/SU-125
https://fiterio.atlassian.net/browse/SU-126
=> Feature/SU-125, SU-125: Reports condonaciones

src/app/products/maximum-credit-rate/maximum-credit-rate-history/maximum-credit-rate-history.component.html
=> [SU-324] Evidencias Sprint 14.1-15.1 (5) / Historial en Maxima Legal

src/app/organization/bulk-import/bulk-import.component.html, src/app/organization/bulk-import/view-bulk-import/bulk-imports.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira task: https://fiterio.atlassian.net/browse/SU-80
=> Feature/SU-80: Aumento definitivo de cupo - Masivo - Base de datos

src/app/reports/run-report/run-report.component.html
=> SU-349 : Evidencias Sprint 14-15 (17) / Round commission amounts!

src/app/clients/clients-view/general-tab/general-tab.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira task: https://fiterio.atlassian.net/browse/SU-86
=> Feature/SU-86: Aumento temporal de cupo - Masivo - Base de datos

src/app/pipes/datetime-format.pipe.ts, src/app/system/manage-jobs/scheduler-jobs/view-history-scheduler-job/view-history-scheduler-job.component.html
=> [SU-360] Time Zone - Jobs

src/app/tasks/checker-inbox-and-tasks-tabs/reschedule-loan/reschedule-loan.component.ts
=> SU-322 : REDIFERIDOS / Seguros Obligatorios y voluntarios

src/app/clients/client-stepper/client-general-step/client-general-step.component.html, src/app/clients/client-stepper/client-general-step/client-general-step.component.ts
=> [SU-358] Incidentes Anteriores (1) - Name and Last name Lenght

src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
Jira task: https://fiterio.atlassian.net/browse/SU-372
=> Feature/SU-372: Massive write-offs: incorrect balance (interest and future charges wrote off)

src/app/core/authentication/authentication.service.ts, src/app/home/home.module.ts, src/app/home/timeout-dialog/idle-timeout.service.spec.ts, src/app/home/timeout-dialog/idle-timeout.service.ts, src/app/home/timeout-dialog/session-timeout-dialog.component.html, src/app/home/timeout-dialog/session-timeout-dialog.component.spec.ts, src/app/home/timeout-dialog/session-timeout-dialog.component.ts, src/app/web-app.component.ts, src/assets/env.js, src/assets/env.template.js, src/environments/environment.prod.ts, src/environments/environment.ts
=> [SU-383]Close session after certaing time / Tiempo de inactividad

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> [SU-385]Payment - Backend Transactions

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira task: https://fiterio.atlassian.net/browse/SU-395
=> Feature/SU-395: Massive import - disable upload files with same filename

src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.ts, src/app/products/loan-products/models/loan-product.model.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
Jira task: https://fiterio.atlassian.net/browse/SU-177
=> Feature/SU-117: SU+ Pay Vehículos: cupo

src/app/organization/claims-writeoffs/claims-writeoffs.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-157 fixed claimed report and error message display

src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.ts
=> SU-408 Sprint 6 - 2 - Clients - Length allowed

src/app/system/system-routing.module.ts
=> Sprint 9 - 3 - Channel Creation

src/app/system/system-routing.module.ts, src/assets/translations/es-MX.json
=> SU-409 : Sprint 9 - 3 - Channel Creation add translation channel

src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html, src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.ts, src/app/system/system-routing.module.ts
=> SU-300 : Implementar Nota de Débito - Producto AJUSTE

src/app/system/manage-channels/channel.component.html, src/app/system/manage-channels/channel.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> [SU-350]Evidencias Sprint 14-15 (18) - Agregar ID de canal (abm canal)

src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.html, src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.scss, src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html, src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.scss
=> [SU-423]Sprint 16-17 - 4 - Screen - Generate Repayment Schedule Space

src/app/loans/common-resolvers/loan-credit-note.resolver.spec.ts, src/app/loans/common-resolvers/loan-credit-note.resolver.ts, src/app/loans/loans-routing.module.ts, src/app/loans/loans-view/loan-account-actions/add-credit-note/add-credit-note.component.html, src/app/loans/loans-view/loan-account-actions/add-credit-note/add-credit-note.component.scss, src/app/loans/loans-view/loan-account-actions/add-credit-note/add-credit-note.component.spec.ts, src/app/loans/loans-view/loan-account-actions/add-credit-note/add-credit-note.component.ts, src/app/loans/loans-view/loan-account-actions/approve-loan/approve-loan.component.html, src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html, src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.ts, src/app/loans/loans-view/loan-accounts-button-config.ts, src/app/loans/loans-view/loans-view.component.html, src/app/loans/loans-view/view-credit-notes/view-credit-notes.component.html, src/app/loans/loans-view/view-credit-notes/view-credit-notes.component.scss, src/app/loans/loans-view/view-credit-notes/view-credit-notes.component.spec.ts, src/app/loans/loans-view/view-credit-notes/view-credit-notes.component.ts, src/app/loans/loans.module.ts, src/app/loans/loans.service.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> [SU-402]Implementar Nota de Crédito

src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
=> SU-431 Sprint 18/19 - 3 / Fix language

src/app/loans/loans-view/loan-account-actions/add-credit-note/add-credit-note.component.ts
=> [SU-402] Implementar Nota de Crédito

src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
=> FDC-59 Allow decimal points on interest rate limit

src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.html, src/app/products/charges/edit-charge/edit-charge.component.ts
=> SU-178: SU+ Pay Vehículos: Rollback charge creation

src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
=> SU-449 : UAT- Puntos de interes / Interest Points

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-450 : Novelty management - add old translation data

src/app/login/login.component.html, src/environments/environment.ts
=> SU-439 Enable multitenant login for migration schema

src/assets/translations/es-MX.json
=> SU-450 : Novelty management

src/app/loans/loans-view/loan-account-actions/charge-off/charge-off.component.html, src/app/loans/loans-view/loan-account-actions/charge-off/charge-off.component.ts
=> SU-450 : Novelty management-update charge-off

src/app/products/loan-product-parameterization/create-loan-product-parameterization/create-loan-product-parameterization.component.html, src/app/products/loan-product-parameterization/create-loan-product-parameterization/create-loan-product-parameterization.component.ts, src/app/products/loan-product-parameterization/edit-loan-product-parameterization/edit-loan-product-parameterization.component.html, src/app/products/loan-product-parameterization/edit-loan-product-parameterization/edit-loan-product-parameterization.component.ts, src/app/products/loan-product-parameterization/view-loan-product-parameterization/view-loan-product-parameterization.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> [SU-198] Facturación electrónica: Parametrizaciones

src/app/products/manage-delinquency-buckets/delinquency-range/create-range/create-range.component.html, src/app/products/manage-delinquency-buckets/delinquency-range/create-range/create-range.component.ts, src/app/products/manage-delinquency-buckets/delinquency-range/delinquency-range.component.html, src/app/products/manage-delinquency-buckets/delinquency-range/delinquency-range.component.ts, src/app/products/manage-delinquency-buckets/delinquency-range/edit-range/edit-range.component.html, src/app/products/manage-delinquency-buckets/delinquency-range/edit-range/edit-range.component.ts, src/app/products/manage-delinquency-buckets/delinquency-range/view-range/view-range.component.html
=> SU-316 : Redefinición de Honorarios / Redefinition of Fees (Honorarios)

src/app/products/collection-house-config/collection-house-config.component.html, src/app/products/collection-house-config/collection-house-config.component.spec.ts, src/app/products/collection-house-config/collection-house-config.component.ts, src/app/products/collection-house-config/collection-house-config.resolver.spec.ts, src/app/products/collection-house-config/collection-house-config.resolver.ts, src/app/products/collection-house-config/collection-house-config.service.spec.ts, src/app/products/collection-house-config/collection-house-config.service.ts, src/app/products/collection-house-config/create-collection-house-config/create-collection-house/create-collection-house.component.html, src/app/products/collection-house-config/create-collection-house-config/create-collection-house/create-collection-house.component.spec.ts, src/app/products/collection-house-config/create-collection-house-config/create-collection-house/create-collection-house.component.ts, src/app/products/collection-house-config/edit-collection-house-config/edit-collection-house-config/edit-collection-house-config.component.html, src/app/products/collection-house-config/edit-collection-house-config/edit-collection-house-config/edit-collection-house-config.component.spec.ts, src/app/products/collection-house-config/edit-collection-house-config/edit-collection-house-config/edit-collection-house-config.component.ts, src/app/products/collection-house-config/view/view-collection-house-config.resolver.spec.ts, src/app/products/collection-house-config/view/view-collection-house-config.resolver.ts, src/app/products/collection-house-config/view/view-collection-house-config/view-collection-house-config.component.html, src/app/products/collection-house-config/view/view-collection-house-config/view-collection-house-config.component.spec.ts, src/app/products/collection-house-config/view/view-collection-house-config/view-collection-house-config.component.ts, src/app/products/products-routing.module.ts, src/app/products/products.component.html, src/app/products/products.module.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-318 : Gestión de Casas de Cobro / Collection House Management

src/app/clients/clients.component.ts
Changed the assignment to get the number of rows, not the number of filtered records.
=> Fix for SU-478

src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.html, src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.scss, src/app/loans/loans-view/original-schedule-tab/original-schedule-tab.component.ts
=> [SU-438] Number in the Original Calendar

src/app/system/external-services/collectionhousehistory/collectionhousehistory.component.html, src/app/system/external-services/collectionhousehistory/collectionhousehistory.component.spec.ts, src/app/system/external-services/collectionhousehistory/collectionhousehistory.component.ts, src/app/system/external-services/collectionhousehistory/collectionhousehistory.resolver.spec.ts, src/app/system/external-services/collectionhousehistory/collectionhousehistory.resolver.ts, src/app/system/external-services/collectionhousehistory/edit-collectionhousehistory/edit-collectionhousehistory.component.html, src/app/system/external-services/collectionhousehistory/edit-collectionhousehistory/edit-collectionhousehistory.component.spec.ts, src/app/system/external-services/collectionhousehistory/edit-collectionhousehistory/edit-collectionhousehistory.component.ts, src/app/system/external-services/external-services.component.html, src/app/system/system-routing.module.ts, src/app/system/system.module.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> SU-319 : Actualización de casas de cobro para clientes

src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.html, src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
=> SU-487 : Vehículo - Seguro endosado

src/app/clients/clients-view/address-tab/address-tab.component.ts
=> EA-62 Show name in add address drop down

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
SUP-462: Restrict deletion of code values in use
=> SUP-462: Restrict deletion of code values in use

src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.html, src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts, src/app/products/interest-rates/create-interest-rate/create-interest-rate.component.html, src/app/products/interest-rates/create-interest-rate/create-interest-rate.component.ts, src/app/products/interest-rates/edit-interest-rate/edit-interest-rate.component.html, src/app/products/interest-rates/edit-interest-rate/edit-interest-rate.component.ts, src/app/products/interest-rates/interest-rate-history/interest-rate-history.component.html, src/app/products/interest-rates/interest-rate-history/interest-rate-history.component.ts, src/app/products/interest-rates/view-interest-rate/view-interest-rate.component.html, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> EA-65 Boundary to interest rate

src/app/products/manage-delinquency-buckets/delinquency-range/create-range/create-range.component.ts, src/app/products/manage-delinquency-buckets/delinquency-range/edit-range/edit-range.component.ts
SU-518: Relax dilinquency range validation to allow 0%
=> SU-518: Relax dilinquency range validation to allow 0%

src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/edit-charge/edit-charge.component.html
=> EA-113 Disable the mandatory options for Insurance Charge

src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.html, src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.ts
SU-519: Implement penalty start date
=> SU-519: Implement penalty start date

src/app/products/charges/charges.component.html, src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/edit-charge/edit-charge.component.ts, src/app/products/charges/view-charge/view-charge.component.html, src/app/products/interest-rates/create-interest-rate/create-interest-rate.component.html, src/app/products/interest-rates/create-interest-rate/create-interest-rate.component.ts, src/app/products/interest-rates/edit-interest-rate/edit-interest-rate.component.html, src/app/products/interest-rates/edit-interest-rate/edit-interest-rate.component.ts, src/app/products/interest-rates/interest-rates.component.html, src/app/products/interest-rates/view-interest-rate/view-interest-rate.component.html
=> EA-112 Make amount to 8 decimal points from default 2 decimal places

src/app/system/external-services/email/edit-email/edit-email.component.html, src/app/system/external-services/email/edit-email/edit-email.component.ts, src/app/system/external-services/email/email.component.ts
=> SU-470: Mail Configuration - Remove authentification

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
=> EA-112 Add Validation to current balance vs min and max rate

src/app/organization/claims-writeoffs/claims-writeoffs.component.html
Jira task: https://fiterio.atlassian.net/browse/SU-479
=> Bug/SU-479: Fix Claim and punishment

src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.html, src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts, src/app/loans/loans-account-stepper/loans-account-terms-step/loans-account-terms-step.component.ts
feature/EA-69 - Crear cargo Mi Pyme desembolso para créditos basados en el monto del desembolso
=> feature/EA-69 - Crear cargo Mi Pyme desembolso para créditos basados en el monto del desembolso

src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.html, src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
feature/EA-116 - Crear cargo Mi Pyme - Capital pendiente  para créditos basados en el monto del desembolso
=> feature/EA-116 - Crear cargo Mi Pyme - Capital pendiente  para créditos basados en el monto del desembolso

src/app/core/utils/datatables.ts, src/app/shared/tabs/entity-datatable-tab/datatable-single-row/datatable-single-row.component.html
feature/EA-149-150-151-152-153 - Some Loans Datatables
=> feature/EA-149-150-151-152-153 - Some Loans Datatables

src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
fix/EA-69 - Switch products charges + adjust charge amount
=> fix/EA-69 - Switch products charges + adjust charge amount

src/app/products/loan-products/common/loan-product-summary/loan-product-summary.component.html
=> fix/EA-201 - Modify label

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/authentication/authentication.interceptor.ts, src/app/core/authentication/authentication.service.ts, src/app/login/login-form/login-form.component.html, src/app/login/login-form/login-form.component.ts, src/app/login/login-routing.module.ts, src/app/login/login.module.ts, src/app/login/microsoft-azure-ad/auth-config.ts, src/app/login/microsoft-azure-ad/redirect/redirect.component.html, src/app/login/microsoft-azure-ad/redirect/redirect.component.scss, src/app/login/microsoft-azure-ad/redirect/redirect.component.spec.ts, src/app/login/microsoft-azure-ad/redirect/redirect.component.ts, src/assets/env.js, src/assets/env.template.js, src/assets/translations/en-US.json, src/assets/translations/es-MX.json, src/environments/environment.prod.ts, src/environments/environment.ts
Jira task: https://fiterio.atlassian.net/browse/EA-119
=> Feature/EA-119: Add implementation of AD on fineract

src/app/login/login-form/login-form.component.ts
Jira task: https://fiterio.atlassian.net/browse/EA-204
=> Feature/EA-87: Configure sonar

.github/workflows/build-fiter-version.yml, Dockerfile, src/environments/environment.ts
Jira task: https://fiterio.atlassian.net/browse/EA-87
=> Feature/EA-87: Integration with Active Directory(Authentication)

src/app/products/loan-product-parameterization/create-loan-product-parameterization/create-loan-product-parameterization.component.html, src/app/products/loan-product-parameterization/create-loan-product-parameterization/create-loan-product-parameterization.component.ts, src/app/products/loan-product-parameterization/edit-loan-product-parameterization/edit-loan-product-parameterization.component.html, src/app/products/loan-product-parameterization/edit-loan-product-parameterization/edit-loan-product-parameterization.component.ts, src/assets/translations/en-US.json, src/assets/translations/es-MX.json
feature/SU-580 - FE -Adjustments for Billing (Facturación) rango de numeración habilitada hasta
=> feature/SU-580 - FE -Adjustments for Billing (Facturación) rango de numeración habilitada hasta

src/assets/translations/es-MX.json
fix/SU-563 - Fix HONORARIOS LABEL in every places
=> fix/SU-563 - Fix HONORARIOS LABEL in every places

src/assets/translations/en-US.json, src/assets/translations/es-MX.json
feature/EA-218-2 - Revolving credit: Disbursement - Repayment Date mandatory
=> feature/EA-218-2 - Revolving credit: Disbursement - Repayment Date mandatory

src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts
feature/EA-220 - Multiple charges Capital pendiente mi pyme for the same loan account
=> feature/EA-220 - Multiple charges Capital pendiente mi pyme for the same loan account

src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.ts
feature/EA-219-3 - Create client: Cupo by default
=> feature/EA-219-3 - Create client: Cupo by default

package-lock.json, src/environments/.env.ts
=> [EA-91] Deployment vulnerability

src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.spec.ts, src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.ts
=>  Deployment vulnerability

src/app/clients/client-stepper/client-datatable-step/client-datatable-step.component.ts, src/app/clients/clients-view/general-tab/general-tab.component.html
=> fix/EA-245 - Crear cliente

src/app/loans/loans-view/transactions/view-transaction/loan-transaction-general-tab/loan-transaction-general-tab.component.html
=> [EA-253] Reverse payment

src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
feature/EA-243-2 - Add Seguro Vida to loan schedule preview
=> feature/EA-243-2 - Add Seguro Vida to loan schedule
